config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get     'login'   => 'sessions#new'
    post    'login'   => 'sessions#create'
    delete  'logout'  => 'sessions#destroy'
    resources :admins
    resources :events do
      post :import, on: :member
      get :pay, on: :member
    end
    resources :users do
      get :active, on: :member
      get :inactive, on: :member
    end
    resources :customers
    resources :orders
    root 'welcome#index'
  end

  namespace :api do
    resources :events, only: [:index, :show], defaults: {format: :json}
    resources :users ,only: [], defaults: {format: :json} do
      patch :update_profile, on: :collection
      get :get_info, on: :collection
    end
    resources :customers, only: :create, defaults: {format: :json}
    resources :orders, only: [:create, :index], defaults: {format: :json}
    get 'wx_get_jsapi_ticket' => 'users#wx_get_jsapi_ticket'
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  HEADERS = ["title", "amount", "quota", "effective_date", "expire_date", "state"]
  mount_uploader :image, ImageUploader
  STATES = ["有效", "待审核", "无效"]

  has_many :orders
  validates :quota, numericality: {greater_than: 0 }

  def engaged
    orders.count
  end

  def available_quota
    quota - orders.count
  end
end

app/controllers/admin/events_controller.rb
require 'net/http'
require 'cgi'
require 'json'
class Admin::EventsController < Admin::BaseController
  def index
    @events = Event.order(updated_at: :desc)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to admin_events_url
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to admin_events_url
    else
      render 'edit'
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to admin_events_url
  end

  def show
    @event = Event.find(params[:id])
  end

  def import
    require 'csv'
    @event = Event.find(params[:id])
    file = params[:file]
    cells = []
    CSV.foreach(file.path, headers: true) do |row|
      next if !row.to_hash.blank?
      # find user according cell
      user = User.find_by(cell: row.to_hash["cell"])
      # find only one order
      order = user.orders.find_by(event_id: params[:id]) if user
      if order
        if order.confirm
          cells << row.to_hash["cell"]
        end
      end 
    end
    redirect_to admin_event_url(@event), notice: "#{cells.to_s}成功导入"
  end

  def pay
    @event = Event.find(params[:id])


    domain = Rails.env.development? ? '139.196.233.121' : '127.0.0.1'
    path = '/wechat/pay.php'
    port = '8080'
    @event.orders.each do |order|
      if order.state == "待派发"
        user = order.user
        parameters = {
          openid: user.openid,
          act_name: @event.title,
          send_name: "淘福利",
          total_amount: order.amount * 100
        }
        res = http_get(domain, path, port, parameters)
        if JSON.parse(res)["return_code"] == "SUCCESS"
          order.pay
        end
      end
    end
    
    redirect_to admin_event_url(@event)
  end

  private
    def event_params
      params.require(:event).permit(
        :title, :url, :image, :amount,
        :effective_date, :expire_date, 
        :state, :quota, :content, 
        :official_benefit, :additional_benefit)
    end

    def http_get(domain,path, port, params)
        return Net::HTTP.get(domain, "#{path}?".concat(params.collect { |k,v| "#{k}=#{CGI::escape(v.to_s)}" }.join('&')), port ) if not params.nil?
        return Net::HTTP.get(domain, path)
    end
end

app/controllers/api/events_controller.rb
class Api::EventsController < Api::BaseController
  skip_before_action :authenticate_user!
  def index
    @q = Event.ransack(state_eq: "有效", effective_date_lteq: Date.today, expire_date_gteq: Date.today)
    @events = @q.result.order(updated_at: :desc)
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/views/admin/events/_event.html.erb
<tr>
  <td><%= link_to image_tag(event.image_url(:thumb)), event.image_url %></td>
  <% Event::HEADERS.each do |column| %>
    <td><%= event.send(column) %></td>
  <% end %>
  <td><%= link_to t(:url), event.url %></td>
  <td><%= truncate event.content %></td>
  <td><%= truncate event.official_benefit %></td>
  <td><%= truncate event.additional_benefit %></td>
  <td><%= I18n.l(event.created_at, format: :long) %></td>
  <td><%= I18n.l(event.updated_at, format: :long) %></td>
  <td><%= link_to t(:edit), edit_admin_event_path(event) %></td>
  <td><%= link_to t(:destroy), admin_event_path(event), method: :delete, data: {confirm: t(:are_you_sure)} %></td>
  <td><%= link_to t(:show), admin_event_path(event) %></td>
  <td><%= link_to t(:pay), pay_admin_event_path(event), data: {confirm: t(:are_you_sure)} %></td>
</tr>

app/views/admin/events/_form.html.erb
<%= simple_form_for([:admin, @event]) do |f| %>
<%= f.input :title %>
<%= f.input :url %>
<%= f.input :image %>
<%= f.input :amount %>
<%= f.input :quota %>
<%= f.input :effective_date, html5: true %>
<%= f.input :expire_date, html5: true %>
<%= f.input :state, collection: Event::STATES %>
<p><strong style="color:red">!!下面三个字段不要写序号!!</strong></p>
<%= f.input :content,hint: "请不要写序号", :input_html => {:rows => 10} %>
<%= f.input :official_benefit, hint: "请不要写序号", :input_html => {:rows => 10} %>
<%= f.input :additional_benefit, hint: "请不要写序号", :input_html => {:rows => 10} %>
<%= f.button :submit %>
<% end %>

<%= link_to t(:back), :back %>

app/views/admin/events/index.html.erb
<div class="col-md-10">
  <h3><%= t(:event_list) %></h3>
</div>
<div class="col-md-2">
  <%= link_to t(:new_event), new_admin_event_path, class: "btn btn-danger" %>
</div>
<div class="col-md-12">
  <table class="table">
    <thead>
      <tr>
        <th><%= Event.human_attribute_name(:image) %></th>
        <% Event::HEADERS.each do |column| %>
          <th><%= Event.human_attribute_name(column) %></th>
        <% end %>
        <th><%= Event.human_attribute_name(:url) %></th>
        <th><%= Event.human_attribute_name(:content) %></th>
        <th><%= Event.human_attribute_name(:official_benefit) %></th>
        <th><%= Event.human_attribute_name(:additional_benefit) %></th>
        <th><%= Event.human_attribute_name(:created_at) %></th>
        <th><%= Event.human_attribute_name(:updated_at) %></th>
        <th colspan="3"><%= t(:operations) %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @events %>
    </tbody>
  </table>
</div>

app/views/admin/events/show.html.erb
<h3>Import a CSV File</h3>
  <%= form_tag import_admin_event_path(@event), multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>