config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get     'login'   => 'sessions#new'
    post    'login'   => 'sessions#create'
    delete  'logout'  => 'sessions#destroy'
    resources :admins
    resources :events do
      post :import, on: :member
      get :pay, on: :member
    end
    resources :users do
      get :active, on: :member
      get :inactive, on: :member
    end
    resources :customers
    resources :orders
    root 'welcome#index'
  end

  namespace :api do
    resources :events, only: [:index, :show], defaults: {format: :json}
    resources :users ,only: [], defaults: {format: :json} do
      patch :update_profile, on: :collection
      get :get_info, on: :collection
    end
    resources :customers, only: :create, defaults: {format: :json}
    resources :orders, only: [:create, :index], defaults: {format: :json}
    get 'wx_get_jsapi_ticket' => 'users#wx_get_jsapi_ticket'
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  validates :user_id, presence: true
  validates :event_id, presence: true
  validates :event_id, uniqueness: {scope: :user_id}
  validate :available_quota
  before_create :set_date

  STATES = ["未派发", "待派发", "已派发"]

  state_machine :state, :initial => :'未派发' do
    event :confirm do
      transition :'未派发' => :'待派发'
    end
    event :pay do
      transition :'待派发' => :'已派发'
    end
  end

  private
    def available_quota
      if event.available_quota <= 0
        errors.add(:base, "没有名额")
      end
    end

    def set_date
      self.date = Date.today
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  def index
    @orders = Order.order(updated_at: :desc).page params[:page]
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to admin_orders_url
    else
      render 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_orders_url
    else
      render 'edit'
    end
  end

  def destroy
    Order.find(params[:id]).destroy
    redirect_to admin_orders_url
  end

  private
    def order_params
      params.require(:order).permit(
        :user_id, :event_id, :amount,
        :state, :date)
    end
end

app/controllers/api/orders_controller.rb
class Api::OrdersController < Api::BaseController
  def create
    event = Event.find_by(id: params[:event_id])
    return render json: {message: "找不到该福利"} if event.nil?
    exist_order = Order.find_by(event_id: params[:event_id], user_id: current_user.id)
    return render json: {message: "记录已存在"} if exist_order
    order = current_user.orders.build(event_id: event.id)
    order.amount = event.amount
    order.date = Date.today
    order.state = "未派发"
    if order.save
      render json: {}, status: 201
    else
      return api_error(status: 422)
    end
  end

  def index
    @orders = current_user.orders.order(date: :desc)
  end
end

app/views/admin/orders/_form.html.erb
<div class="col-md-6">
  <%= simple_form_for([:admin, @order]) do |f| %>
    <%= render 'admin/shared/error_messages', object: f.object %>
    <%= f.input :user_id, collection: User.all %>
    <%= f.input :event_id, collection: Event.all %>
    <%= f.input :amount %>
    <%= f.input :state, collection: Order::STATES %>
    <%= f.input :date, html5: true %>
    <%= f.button :submit %>
  <% end %>
</div>
<div class="col-md-12">
  <%= link_to t(:back), :back %>
</div>

app/views/admin/orders/_order.html.erb
<tr>
  <td><%= order.user.name if order.user %></td>
  <td><%= order.event.title if order.event %></td>
  <td><%= order.amount %></td>
  <td><%= order.state %></td>
  <td><%= I18n.l(order.date, format: :long) %></td>
  <td><%= I18n.l(order.created_at, format: :long) %></td>
  <td><%= I18n.l(order.updated_at, format: :long) %></td>
  <td><%= link_to t(:edit), edit_admin_order_path(order) %></td>
  <td><%= link_to t(:destroy), admin_order_path(order), method: :delete, data: {confirm: t(:are_you_sure)} %></td>
</tr>

app/views/admin/orders/edit.html.erb
<%= render 'form' %>

app/views/admin/orders/index.html.erb
<div class="col-md-10">
  <h3><%= t(:order_list) %></h3>
</div>
<div class="col-md-2">
  <%= link_to t(:new_order), new_admin_order_path, class: "btn btn-danger" %>
</div>
<div class="col-md-12">
  <%= paginate @orders %>
  <table class="table">
    <thead>
      <tr>
        <th><%= Order.human_attribute_name(:user_id) %></th>
        <th><%= Order.human_attribute_name(:event_id) %></th>
        <th><%= Order.human_attribute_name(:amount) %></th>
        <th><%= Order.human_attribute_name(:state) %></th>
        <th><%= Order.human_attribute_name(:date) %></th>
        <th><%= Order.human_attribute_name(:created_at) %></th>
        <th><%= Order.human_attribute_name(:updated_at) %></th>
        <th colspan="3"><%= t(:operations) %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @orders %>
    </tbody>
  </table>
  <%= paginate @orders %>
</div>

app/views/admin/orders/new.html.erb
<%= render 'form' %>