config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get     'login'   => 'sessions#new'
    post    'login'   => 'sessions#create'
    delete  'logout'  => 'sessions#destroy'
    resources :admins
    resources :events do
      post :import, on: :member
      get :pay, on: :member
    end
    resources :users do
      get :active, on: :member
      get :inactive, on: :member
    end
    resources :customers
    resources :orders
    root 'welcome#index'
  end

  namespace :api do
    resources :events, only: [:index, :show], defaults: {format: :json}
    resources :users ,only: [], defaults: {format: :json} do
      patch :update_profile, on: :collection
      get :get_info, on: :collection
    end
    resources :customers, only: :create, defaults: {format: :json}
    resources :orders, only: [:create, :index], defaults: {format: :json}
    get 'wx_get_jsapi_ticket' => 'users#wx_get_jsapi_ticket'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  HEADERS = ["openid", "name", "gender", "cell", "email", "state"]
  validates :openid, presence: true

  has_many :orders
  
  state_machine :state, :initial => :'权益未激活' do
    event :active do
      transition :'权益未激活' => :'权益已激活'
    end
    event :inactive do
      transition :'权益已激活' => :'权益未激活'
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.order(updated_at: :desc).page params[:page]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.openid = params[:user][:openid]
    if @user.save
      redirect_to admin_users_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_url
    else
      render 'edit'
    end
  end

  def active
    user = User.find(params[:id])
    user.active
    redirect_to admin_users_url
  end

  def inactive
    user = User.find(params[:id])
    user.inactive
    redirect_to admin_users_url
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to admin_users_url
  end
  private
    def user_params
      params.require(:user).permit(
        :name, :gender, :cell, :email)
    end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  skip_before_action :authenticate_user!, only: [:wx_get_jsapi_ticket]
  def update_profile
    @user = current_user
    if @user.update(user_params)
      @user.active if @user.name && @user.gender && @user.cell && @user.email
      render 'get_info'
    else
      return api_error(status: 422)
    end
  end

  def get_info
    @user = current_user
  end

  def wx_get_jsapi_ticket
    jsapi_ticket = ""
    if Ticket.first && !Ticket.first.ticket.nil? && Ticket.first.expires_at > Time.current
      jsapi_ticket = Ticket.first.ticket
    else
      uri = URI("https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=#{ENV["WECHAT_APP_ID"]}&secret=#{ENV["WECHAT_APP_SECRET"]}")
      res = Net::HTTP.get_response(uri)
      json =  JSON.parse(res.body.gsub(/[\u0000-\u001f]+/, ''))
      access_token = json["access_token"]

      ticket_uri = URI("https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=#{access_token}&type=jsapi")
      ticket_res = Net::HTTP.get_response(ticket_uri)
      ticket_json = JSON.parse(ticket_res.body.gsub(/[\u0000-\u001f]+/, ''))
      jsapi_ticket = ticket_json["ticket"]
      Ticket.delete_all
      Ticket.create(
        ticket: jsapi_ticket,
        token: access_token,
        expires_at: Time.current + 1.hours
        )
    end

    if jsapi_ticket == ""
      render json: {message: "error"}
    else
      timestamp = Time.now.to_i
      wxnonceStr = "taofuli"
      wxOri = Digest::SHA1.hexdigest("jsapi_ticket=#{jsapi_ticket}&noncestr=#{wxnonceStr}&timestamp=#{timestamp}&url=#{params[:url]}")
      render json: {timestamp: timestamp, noncestr: wxnonceStr, signature: wxOri, appid: ENV["WECHAT_APP_ID"], access_token: Ticket.first.token}
    end
  end

  private
    def user_params
      params.permit(:name, :gender, :cell, :email)
    end
end

app/views/admin/users/_form.html.erb
<div class="col-md-6">
  <%= simple_form_for([:admin, @user]) do |f| %>
    <%= f.input :openid, disabled: !@user.new_record? %>
    <%= f.input :name %>
    <%= f.input :gender %>
    <%= f.input :cell %>
    <%= f.input :email %>
    <%= f.input :state, disabled: true %>
    <%= f.button :submit %>
  <% end %>
</div>
<div class="col-md-12">
  <%= link_to t(:back), :back %>
</div>

app/views/admin/users/_user.html.erb
<tr>
  <% User::HEADERS.each do |column| %>
    <td><%= user.send(column) %></td>
  <% end %>
  <td><%= I18n.l(user.created_at, format: :long) %></td>
  <td><%= I18n.l(user.updated_at, format: :long) %></td>
  <% if user.state == "权益未激活" %>
    <td><%= link_to t(:active), active_admin_user_path(user) %></td>
  <% else %>
    <td><%= link_to t(:inactive), inactive_admin_user_path(user) %></td>
  <% end %>
  <td><%= link_to t(:edit), edit_admin_user_path(user) %></td>
  <td><%= link_to t(:destroy), admin_user_path(user), method: :delete, data: {confirm: t(:are_you_sure)} %></td>
</tr>

app/views/admin/users/index.html.erb
<div class="col-md-10">
  <h3><%= t(:user_list) %></h3>
</div>
<div class="col-md-2">
  <%= link_to t(:new_user), new_admin_user_path, class: "btn btn-danger" %>
</div>
<div class="col-md-12">
  <%= paginate @users %>
  <table class="table">
    <thead>
      <tr>
        <% User::HEADERS.each do |column| %>
          <th><%= User.human_attribute_name(column) %></th>
        <% end %>
        <th><%= User.human_attribute_name(:created_at) %></th>
        <th><%= User.human_attribute_name(:updated_at) %></th>
        <th colspan="3"><%= t(:operations) %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @users %>
    </tbody>
  </table>
  <%= paginate @users %>
</div>