config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get     'login'   => 'sessions#new'
    post    'login'   => 'sessions#create'
    delete  'logout'  => 'sessions#destroy'
    resources :admins
    resources :events do
      post :import, on: :member
      get :pay, on: :member
    end
    resources :users do
      get :active, on: :member
      get :inactive, on: :member
    end
    resources :customers
    resources :orders
    root 'welcome#index'
  end

  namespace :api do
    resources :events, only: [:index, :show], defaults: {format: :json}
    resources :users ,only: [], defaults: {format: :json} do
      patch :update_profile, on: :collection
      get :get_info, on: :collection
    end
    resources :customers, only: :create, defaults: {format: :json}
    resources :orders, only: [:create, :index], defaults: {format: :json}
    get 'wx_get_jsapi_ticket' => 'users#wx_get_jsapi_ticket'
  end

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t(:title), admin_root_url, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if admin_logged_in? %>
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if params[:controller] == 'admin/events' %>"><%= link_to Event.model_name.human, admin_events_path %></a></li>
          <li class="<%= 'active' if params[:controller] == 'admin/users' %>"><%= link_to User.model_name.human, admin_users_path %></a></li>
          <li class="<%= 'active' if params[:controller] == 'admin/customers' %>"><%= link_to Customer.model_name.human, admin_customers_path %></a></li>
          <li class="<%= 'active' if params[:controller] == 'admin/orders' %>"><%= link_to Order.model_name.human, admin_orders_path %></a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if params[:controller] == 'admin/admins' %>"><%= link_to Admin.model_name.human, admin_admins_path %></li>
          <li><%= link_to t('logout'), admin_logout_path, method: :delete %></li>
        </ul>

      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t('login'), admin_login_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title><%= t(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
  

</body>
</html>